---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: kbot
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: kbot
#   namespace: kbot
# spec:
#   interval: 1m0s
#   releaseName: kbot
#   targetNamespace: kbot
#   chartRef:
#     kind: OCIRepository
#     name: kbot
#     namespace: kbot
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: OCIRepository
# metadata:
#   name: kbot
#   namespace: kbot
# spec:
#   interval: 1m0s
#   url: oci://ghcr.io/yurii-bielodied/charts/kbot
#   ref:
#     semver: ">=1.0.0"
